version: '3.4'

services:
 webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    networks:
      - bar
 db:
   image: postgres:11.2
   ports:
     - "5432:5432"
   volumes:
     - pgdata:/var/lib/postgresql/data
     - pgconf:/etc/postgresql
     - pglog:/var/log/postgresql
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=docker
   networks:
     - bar
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
networks:
  bar: